### 手写1-10 分类

In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
import tensorflow as tf # 导入 TF 库
from tensorflow import keras # 导入 TF 子库
from tensorflow.keras import layers, optimizers, datasets # 导入 TF 子库

In [4]:
y = tf.constant([0,1,2,3]) # 数字编码
y = tf.one_hot(y, depth=10) # one-hot 编码
print(y)

tf.Tensor(
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]], shape=(4, 10), dtype=float32)


In [20]:
# load_data()函数返回两个元组(tuple)对象
# 第一个是训练集，第二个是测试集，每个 tuple的第一个元素是多个训练图片数据X，第二个元素是训练图片对应的类别数字Y。
# 其中训练集X的大小为(60000,28,28)，代表了 60000 个样本，每个样本由 28 行、28 列构成，由于是灰度图片，故没有 RGB 通道
# 训练集Y的大小为(60000, )，代表了这 60000 个样本的标签数字，每个样本标签用一个 0~9 的数字表示。
# 测试集X  的大小为(10000,28,28)，代表了10000 张测试图片，Y 的大小为(10000,)
(x, y), (x_val, y_val) = datasets.mnist.load_data() 
x = tf.convert_to_tensor(x, dtype=tf.float32) / 255.
y = tf.convert_to_tensor(y, dtype=tf.int32)
y = tf.one_hot(y, depth=10)
print(x.shape, y.shape)
# 构建数据集对象
train_dataset = tf.data.Dataset.from_tensor_slices((x, y))
# 批量训练
train_dataset = train_dataset.batch(100)

# 当一个完整的数据集通过了神经网络一次并且返回了一次，这个过程称为一次epoch
# batch size = 100, 每100个数据做完后更新模型权重
# 每个 Epoch 中发生模型权重更新的次数： 60000/100 = 600

model = keras.Sequential([ 
    layers.Dense(512, activation='relu'),
    layers.Dense(256, activation='relu'),
    layers.Dense(10)])

optimizer = optimizers.SGD(learning_rate=0.001)

def train_epoch(epoch):
    # Step4.loop
    for step, (x, y) in enumerate(train_dataset):
        with tf.GradientTape() as tape:
            # [b, 28, 28] => [b, 784]
            x = tf.reshape(x, (-1, 28*28))
            # Step1. compute output
            # [b, 784] => [b, 10]
            out = model(x)
            # Step2. compute loss
            loss = tf.reduce_sum(tf.square(out - y)) / x.shape[0]

        # Step3. optimize and update w1, w2, w3, b1, b2, b3
        grads = tape.gradient(loss, model.trainable_variables)
        # w' = w - lr * grad
        optimizer.apply_gradients(zip(grads, model.trainable_variables))

        if step % 599 == 0:
            print(epoch, step, 'loss:', loss.numpy())

def train():
    for epoch in range(10):
        train_epoch(epoch)

if __name__ == '__main__':
    train()

(60000, 28, 28) (60000, 10)
0 0 loss: 1.9094833
0 599 loss: 0.6473389
1 0 loss: 0.4946021
1 599 loss: 0.534208
2 0 loss: 0.40354034
2 599 loss: 0.47756314
3 0 loss: 0.3614713
3 599 loss: 0.4391111
4 0 loss: 0.3344179
4 599 loss: 0.40941325
5 0 loss: 0.31458706
5 599 loss: 0.38550583
6 0 loss: 0.29878503
6 599 loss: 0.36567688
7 0 loss: 0.28550845
7 599 loss: 0.34863272
8 0 loss: 0.2742657
8 599 loss: 0.33375388
9 0 loss: 0.26468924
9 599 loss: 0.32082027


In [ ]:
0 599 loss: 1.7500073
1 599 loss: 1.6735139
2 599 loss: 1.6064577
3 599 loss: 1.547463
4 599 loss: 1.4951135
5 599 loss: 1.448603
6 599 loss: 1.4072496
7 599 loss: 1.370266
8 599 loss: 1.337115
9 599 loss: 1.3072007

In [ ]:
0 0 loss: 1.9094833
0 599 loss: 0.6473389
1 0 loss: 0.4946021
1 599 loss: 0.534208
2 0 loss: 0.40354034
2 599 loss: 0.47756314
3 0 loss: 0.3614713
3 599 loss: 0.4391111
4 0 loss: 0.3344179
4 599 loss: 0.40941325
5 0 loss: 0.31458706
5 599 loss: 0.38550583
6 0 loss: 0.29878503
6 599 loss: 0.36567688
7 0 loss: 0.28550845
7 599 loss: 0.34863272
8 0 loss: 0.2742657
8 599 loss: 0.33375388
9 0 loss: 0.26468924
9 599 loss: 0.32082027