### 手写1-10 分类

In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
import tensorflow as tf # 导入 TF 库
from tensorflow import keras # 导入 TF 子库
from tensorflow.keras import layers, optimizers, datasets # 导入 TF 子库

In [4]:
y = tf.constant([0,1,2,3]) # 数字编码
y = tf.one_hot(y, depth=10) # one-hot 编码
print(y)

tf.Tensor(
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]], shape=(4, 10), dtype=float32)


In [2]:
(x, y), (x_val, y_val) = datasets.mnist.load_data() 
x = tf.convert_to_tensor(x, dtype=tf.float32) / 255.
y = tf.convert_to_tensor(y, dtype=tf.int32)
y = tf.one_hot(y, depth=10)
print(x.shape, y.shape)
train_dataset = tf.data.Dataset.from_tensor_slices((x, y))
train_dataset = train_dataset.batch(200)

model = keras.Sequential([ 
    layers.Dense(512, activation='relu'),
    layers.Dense(256, activation='relu'),
    layers.Dense(10)])

optimizer = optimizers.SGD(learning_rate=0.001)

def train_epoch(epoch):
    # Step4.loop
    for step, (x, y) in enumerate(train_dataset):
        with tf.GradientTape() as tape:
            # [b, 28, 28] => [b, 784]
            x = tf.reshape(x, (-1, 28*28))
            # Step1. compute output
            # [b, 784] => [b, 10]
            out = model(x)
            # Step2. compute loss
            loss = tf.reduce_sum(tf.square(out - y)) / x.shape[0]

        # Step3. optimize and update w1, w2, w3, b1, b2, b3
        grads = tape.gradient(loss, model.trainable_variables)
        # w' = w - lr * grad
        optimizer.apply_gradients(zip(grads, model.trainable_variables))

        if step % 100 == 0:
            print(epoch, step, 'loss:', loss.numpy())

def train():
    for epoch in range(30):
        train_epoch(epoch)

if __name__ == '__main__':
    train()

(60000, 28, 28) (60000, 10)
0 0 loss: 1.7769939
0 100 loss: 0.91432387
0 200 loss: 0.6788497
1 0 loss: 0.6845456
1 100 loss: 0.6906438
1 200 loss: 0.5369684
2 0 loss: 0.568016
2 100 loss: 0.6000438
2 200 loss: 0.47479874
3 0 loss: 0.50945455
3 100 loss: 0.5460924
3 200 loss: 0.43652236
4 0 loss: 0.4714886
4 100 loss: 0.5083153
4 200 loss: 0.40885943
5 0 loss: 0.4434973
5 100 loss: 0.48002738
5 200 loss: 0.38729322
6 0 loss: 0.42150116
6 100 loss: 0.45720753
6 200 loss: 0.36970833
7 0 loss: 0.40347776
7 100 loss: 0.43802416
7 200 loss: 0.35497355
8 0 loss: 0.3881899
8 100 loss: 0.42198524
8 200 loss: 0.34233406
9 0 loss: 0.37500107
9 100 loss: 0.4079653
9 200 loss: 0.33141276
10 0 loss: 0.36341202
10 100 loss: 0.39560595
10 200 loss: 0.3217327
11 0 loss: 0.35296082
11 100 loss: 0.38479638
11 200 loss: 0.31309184
12 0 loss: 0.34340134
12 100 loss: 0.3751436
12 200 loss: 0.30532295
13 0 loss: 0.33468276
13 100 loss: 0.36647978
13 200 loss: 0.29830876
14 0 loss: 0.32669163
14 100 loss: 0.3