### 1. 数据类型
##### 数值：标量，向量，矩阵
##### 字符串
##### 布尔

In [2]:
import tensorflow as tf
a = 1.2
aa = tf.constant(1.2) # 创建标量
type(a), type(aa), tf.is_tensor(aa)
aa

<tf.Tensor: id=0, shape=(), dtype=float32, numpy=1.2>

In [9]:
# 向量
x = tf.constant([1,2.,3.3])
print(x)
y = x.numpy()
print(y)

tf.Tensor([1.  2.  3.3], shape=(3,), dtype=float32)
[1.  2.  3.3]


In [14]:
# 矩阵
x1 = tf.constant([[1,2.,3.3],[1,2.,3.3]])
print(x1)
x2 = tf.constant([[[1,2.,3.3],[1,2.,3.3]],[[2,2.,3.3],[3,2.,3.3]]])
print(x2)

tf.Tensor(
[[1.  2.  3.3]
 [1.  2.  3.3]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[[1.  2.  3.3]
  [1.  2.  3.3]]

 [[2.  2.  3.3]
  [3.  2.  3.3]]], shape=(2, 2, 3), dtype=float32)


In [18]:
# 精度不足，溢出
tf.constant(123456789, dtype=tf.int16)

<tf.Tensor: id=19, shape=(), dtype=int16, numpy=-13035>

In [16]:
tf.constant(123456789, dtype=tf.int32)

<tf.Tensor: id=17, shape=(), dtype=int32, numpy=123456789>

In [21]:
import numpy as np
np.pi
print(tf.constant(np.pi, dtype=tf.float32))
print(tf.constant(np.pi, dtype=tf.float64))

tf.Tensor(3.1415927, shape=(), dtype=float32)
tf.Tensor(3.141592653589793, shape=(), dtype=float64)


#### 待优化张量
##### tf.Variable 类型在普通的张量类型基础上添加了 name，trainable 等属性来支持计算图的构建。

In [23]:
a = tf.Variable([[1,2],[3,4]])
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

### 2. 创建张量
##### 从 Numpy, List 对象创建

In [24]:
tf.convert_to_tensor([1,2.])
tf.convert_to_tensor(np.array([[1,2.],[3,4]]))

<tf.Tensor: id=40, shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

##### 创建全 0，全 1 张量 （W b 初始化）

In [35]:
W = tf.zeros([3,2])
b = tf.ones([2,1])
print(W)
print(b)
# 创建与张量 W 形状一样的全 1 张量：
W1= tf.ones_like(W)
print(W1)
# 创建所有元素为 99 的矩阵：
W2 = tf.fill([2,2], 99)
print(W2)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[99 99]
 [99 99]], shape=(2, 2), dtype=int32)


##### 创建已知分布的张量

In [36]:
tf.random.normal([2,2])

<tf.Tensor: id=138, shape=(2, 2), dtype=float32, numpy=
array([[ 0.03223651,  1.3582006 ],
       [-1.1937888 , -1.6794026 ]], dtype=float32)>

In [38]:
# 创建均值为 1，标准差为 2 的正太分布：
tf.random.normal([2,2], mean=1,stddev=2)

<tf.Tensor: id=150, shape=(2, 2), dtype=float32, numpy=
array([[2.3275564 , 1.2319326 ],
       [1.2810699 , 0.96699584]], dtype=float32)>

In [41]:
# 创建采样自区间[0,1]，shape 为[2,2]的矩阵：
tf.random.uniform([2,2],minval=2, maxval=3, dtype=tf.float32)

<tf.Tensor: id=164, shape=(2, 2), dtype=float32, numpy=
array([[2.390289 , 2.8815508],
       [2.2931743, 2.162972 ]], dtype=float32)>

##### 创建序列

In [42]:
tf.range(10)

<tf.Tensor: id=168, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [44]:
tf.range(1,10,delta=2)

<tf.Tensor: id=176, shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [47]:
out = tf.random.uniform([4,10]) #随机模拟网络输出
y = tf.constant([2,3,2,0]) # 随机构造样本真实标签
y = tf.one_hot(y, depth=10) # one-hot 编码
loss = tf.keras.losses.mse(y, out) # 计算每个样本的 MSE
loss = tf.reduce_mean(loss) # 平均 MSE
print(loss)

tf.Tensor(0.40357384, shape=(), dtype=float32)


### 3.典型应用

In [48]:
out = tf.random.uniform([4,10]) #随机模拟网络输出
y = tf.constant([2,3,2,0]) # 随机构造样本真实标签
y = tf.one_hot(y, depth=10) # one-hot 编码
loss = tf.keras.losses.mse(y, out) # 计算每个样本的 MSE
loss = tf.reduce_mean(loss) # 平均 MSE
print(loss)

tf.Tensor(0.29426855, shape=(), dtype=float32)


### 4. 索引与切片

start:end:step 从 start 开始读取到 end(不包含 end)，步长为 step


### 5. 维度变换
Reshape，

In [55]:
x=tf.range(96)
x=tf.reshape(x,[2,4,4,3])
tf.reshape(x,[2,-1])

<tf.Tensor: id=263, shape=(2, 48), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]])>

In [65]:
# 增删维度
x = tf.random.uniform([28,28],maxval=10,dtype=tf.int32)
x = tf.expand_dims(x,axis=0)
x = tf.squeeze(x)
x


<tf.Tensor: id=316, shape=(28, 28), dtype=int32, numpy=
array([[4, 4, 5, 2, 0, 2, 8, 7, 1, 5, 7, 0, 5, 6, 7, 7, 0, 0, 4, 1, 4, 3,
        7, 0, 1, 6, 1, 6],
       [8, 0, 7, 6, 7, 3, 4, 7, 0, 1, 4, 1, 5, 1, 5, 1, 7, 4, 9, 2, 7, 0,
        9, 9, 1, 7, 0, 4],
       [5, 4, 8, 3, 4, 2, 3, 2, 6, 0, 3, 8, 9, 2, 2, 2, 1, 6, 5, 5, 6, 0,
        2, 7, 6, 0, 9, 1],
       [3, 2, 7, 8, 1, 9, 5, 6, 0, 7, 9, 6, 4, 8, 6, 5, 6, 2, 0, 3, 5, 1,
        6, 9, 8, 9, 8, 1],
       [7, 3, 3, 2, 4, 3, 8, 7, 3, 5, 2, 6, 9, 1, 3, 3, 6, 3, 4, 9, 9, 7,
        4, 0, 5, 3, 8, 2],
       [6, 2, 4, 2, 0, 3, 0, 1, 1, 5, 5, 2, 9, 0, 8, 0, 3, 7, 9, 0, 3, 9,
        7, 3, 5, 5, 7, 3],
       [3, 4, 5, 7, 7, 0, 3, 0, 7, 3, 7, 7, 8, 3, 8, 3, 2, 8, 8, 0, 6, 6,
        3, 3, 8, 9, 6, 5],
       [6, 1, 3, 5, 2, 1, 8, 3, 6, 9, 9, 3, 9, 1, 6, 4, 2, 1, 8, 4, 0, 4,
        5, 7, 4, 0, 2, 4],
       [5, 0, 3, 6, 6, 5, 3, 3, 1, 8, 9, 9, 7, 4, 2, 6, 8, 5, 9, 7, 3, 2,
        3, 1, 4, 0, 1, 6],
       [8, 0, 4, 5, 7, 5, 3, 0, 8, 

In [69]:
# 交换维度
x =tf.random.normal([2,32,32,3])
tf.transpose(x,perm=[0,3,1,2])

<tf.Tensor: id=346, shape=(2, 3, 32, 32), dtype=float32, numpy=
array([[[[ 1.57653093e+00,  5.53514421e-01, -7.22166970e-02, ...,
          -2.22616434e-01, -6.74510077e-02,  3.64590228e-01],
         [ 2.47342086e+00, -1.56487394e-02, -4.02609795e-01, ...,
          -8.82047772e-01,  1.20702517e+00, -1.81165302e+00],
         [ 1.16276753e+00, -2.03177184e-01,  5.60336888e-01, ...,
           1.18665814e+00,  6.56760931e-01,  6.55978501e-01],
         ...,
         [ 8.53973150e-01,  7.93928504e-01, -1.93984762e-01, ...,
          -1.25642076e-01,  7.73167551e-01,  3.84109139e-01],
         [ 1.21572244e+00, -6.98395312e-01, -6.90107942e-01, ...,
          -5.56226730e-01,  1.35863340e+00, -1.79937410e+00],
         [-3.86355370e-01,  5.60762823e-01,  8.73597443e-01, ...,
          -7.95942187e-01, -1.03388083e+00, -3.36908013e-01]],

        [[-1.27259040e+00,  1.28873277e+00, -1.48121864e-01, ...,
          -1.26954138e-01,  2.92426467e-01, -1.93788612e+00],
         [ 2.27905318e-0

### 6. Broadcasting

In [4]:
# 操作符+在遇到 shape 不一致的 2 个张量时，会自动考虑将 2 个张量 Broadcasting 到一致的 shape，然后再调用 tf.add 完成张量相加运算
x = tf.random.normal([2,4])
w = tf.random.normal([4,3])
b = tf.random.normal([3])
y = x@w+b
y

<tf.Tensor: id=40, shape=(2, 3), dtype=float32, numpy=
array([[ 5.0188346, -1.2160197,  4.3989935],
       [-2.2437944,  2.8520594, -1.3173838]], dtype=float32)>

In [10]:
A = tf.random.normal([32,1]) 
# 不具备普适性
# B = tf.random.normal([32,2]) 
tf.broadcast_to(A, [2,32,32,3])
# tf.broadcast_to(B, [2,32,32,3])

<tf.Tensor: id=84, shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[-1.0425924, -1.0425924, -1.0425924],
         [-0.9496581, -0.9496581, -0.9496581],
         [ 1.037427 ,  1.037427 ,  1.037427 ],
         ...,
         [ 0.70395  ,  0.70395  ,  0.70395  ],
         [-1.4450053, -1.4450053, -1.4450053],
         [ 1.0629838,  1.0629838,  1.0629838]],

        [[-1.0425924, -1.0425924, -1.0425924],
         [-0.9496581, -0.9496581, -0.9496581],
         [ 1.037427 ,  1.037427 ,  1.037427 ],
         ...,
         [ 0.70395  ,  0.70395  ,  0.70395  ],
         [-1.4450053, -1.4450053, -1.4450053],
         [ 1.0629838,  1.0629838,  1.0629838]],

        [[-1.0425924, -1.0425924, -1.0425924],
         [-0.9496581, -0.9496581, -0.9496581],
         [ 1.037427 ,  1.037427 ,  1.037427 ],
         ...,
         [ 0.70395  ,  0.70395  ,  0.70395  ],
         [-1.4450053, -1.4450053, -1.4450053],
         [ 1.0629838,  1.0629838,  1.0629838]],

        ...,

        [[-1.0425924, -1.0425

### 前向传播实战
 𝑢𝑡 = 𝑟𝑒𝑙𝑢{𝑟𝑒𝑙𝑢{𝑟𝑒𝑙𝑢[𝑋@𝑊1 + 𝑏1]@𝑊2 + 𝑏2}@𝑊 + 𝑏 }

In [11]:
w1 = tf.Variable(tf.random.truncated_normal([784, 256], stddev=0.1))
b1 = tf.Variable(tf.zeros([256]))
w2 = tf.Variable(tf.random.truncated_normal([256, 128], stddev=0.1))
b2 = tf.Variable(tf.zeros([128]))
w3 = tf.Variable(tf.random.truncated_normal([128, 10], stddev=0.1))
b3 = tf.Variable(tf.zeros([10]))
w1

<tf.Variable 'Variable:0' shape=(784, 256) dtype=float32, numpy=
array([[-0.13521983, -0.02175665,  0.11128136, ..., -0.06741329,
        -0.08149116, -0.00654633],
       [-0.05740541, -0.08185589,  0.18429135, ..., -0.08993555,
        -0.11783524, -0.02971671],
       [ 0.06152431, -0.07288032, -0.01002131, ..., -0.13722728,
        -0.16153447, -0.01725897],
       ...,
       [ 0.17084886,  0.1618271 ,  0.02395646, ...,  0.04854235,
        -0.03832098, -0.03194404],
       [-0.09677567, -0.03402415, -0.11851686, ...,  0.02497125,
         0.00790654, -0.18145515],
       [ 0.06814697,  0.04355044,  0.03259075, ..., -0.04465717,
         0.15669219,  0.0539772 ]], dtype=float32)>